use ttn_affiliation_body;
create schema if not exists ttn_affiliation_body;
Create user 'ttn_db_user'@'localhost' identified by 'a';
Create user 'ttn_app_user'@'localhost' identified by 'b';
grant select,create,update,insert,grant option on ttn_affiliation_body to 'ttn_db_user' @'localhost' identified by 'a';
grant select,insert,update,delete on ttn_affiliation_body.* to 'ttn_app_user' @'localhost' identified by 'b';
Create table if not exists user(user_id int(10) auto_increment PRIMARY KEY not null,role_id int(10) not null,foreign key(role_id) references roles(role_id),batch_id int(10) not null,foreign key(batch_id) references batch(batch_id),name varchar(50) NOT NULL,email varchar(50) NOT NULL,date_of_application date NOT NULL,status_of_application boolean NOT NULL);
select * from user;
Create table if not exists roles(role_id int(10) primary key not null,role varchar(50));
select * from roles;
Create table if not exists batch(batch_id int(10) primary key not null,batch_year varchar(50),no_of_students int(10) not null);
select * from batch;
insert into user values(101,01,1001,'rohit','rohitsingh10@gmail.com','2010/05/22',0);
insert into user values(102,01,1002,'sugandh','suganhsahu@gmail.com','2008/05/2',1);
insert into user values(103,02,1001,'arpit','arpit10@gmail.com','2009/07/21',1);
insert into roles values(01,'training_partner');
insert into roles values(02,'assessment');
insert into batch values(1001,'2001',60);
insert into batch values(1002,'2011',160);
