select app_id from appp_status union select appc_id from app_comment;
select app_id from appp_status union all select appc_id from app_comment;
select * from appp_status;
select name from user where roll_id in (select roll_id from roles where r_name='TP');
select * from roles;
select name from user where date_apply not in ('2017/05/09');
select name from user where roll_id =some (select roll_id from roles where r_name='TP');
select name from user where exists (select roll_id from roles where r_name='TP');
select name from user where roll_id =all (select roll_id from roles where r_name='TP');
show tables;
select * from user;
select count(distinct contact) from user;
