create database if not exists ttn_affiliation_body;
use ttn_affiliation_body;
grant grant option,create,select,update,insert on ttn_affiliation_body.* to 'ttn_db_user'@'localhost' identified by '12345';
grant select,update,insert,delete on ttn_affiliation_body.* to 'ttn_app_user'@'localhost' identified by '12345';
create table if not exists application(id int(20) auto_increment unique,body_name varchar(200) primary key,date_of_apply date);
create table if not exists type_application(body_name varchar(200),foreign key(body_name) references application(body_name),body_type enum('training partner','asessment body') primary key,status1 varchar(200) default'pending');
create table if not exists role(body_name varchar(200),body_type enum('training partner','asessment body'),foreign key(body_type) references type_application(body_type),foreign key(body_name) references application(body_name));
create table if not exists training_body(body_type enum('training partner'),foreign key(body_type) references type_application(body_type),start_date date,end_date date,student_name varchar(200) primary key,batch_size varchar(200));
create table if not exists asessment_body(body_type enum('asessment body'),foreign key(body_type) references type_application(body_type),start_date date,end_date date,person enum('busy','available') primary key);
create table if not exists allocated_to(person enum('busy'),allocated_to varchar(200),foreign key(allocated_to) references training_body(student_name),foreign key(person) references asessment_body(person));
